name: serveur_calcul_python
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - debugpy
  - scikit-image
  - sqlalchemy
  - pandas
  - lxml
  - openpyxl
  - psycopg2
  - git
  - geopandas
  - typing
  - xlrd
  - matplotlib
  - geoalchemy2
  - typing-extensions
  - pytest
  - coverage
  - gdal
  - fiona
